# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zhangyanlfNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'HandyJSON'
  pod 'Kingfisher'
  use_frameworks!

end
